########## Universal
scan_stride: 1
resolution: 0.2
ds_resolution: 0.01
visualization_pose_target: rellis
visualization_pose_dir: /workspace/rellis_04_pose/                                              # SERVER
visualization_saving_map_freq: 1
block_depth: 2
max_range: -1
prefix: merged

unc_thres: 0.9
# unc_thres: 0.5

# 之前默认值
# ell: 0.3
# sf2: 1.0 #之前硬编码确定
# ell: 0.2 #项目自带的注释值

# HMC使用0004序列的部分点云推理得到
ell: 1.1489
sf2: 0.4188

########## Remapping
# Original
# mapping_mode: 102
# num_class: 20
# Remapping
mapping_mode: 9
num_class: 9

########## Individual
scan_start: 1
# 00004 full
scan_num: 30
dir: /home/xzy/Downloads/convertedRellis/rellisv3_edl_train-4/05_pVec_pcd/00004/                          # SERVER, rellisv3_edlt17_train-4, BKIFormatter30